let words: string[] = [
    'COMPUTADORA',
    'AGUACATE',
    'PAPAYA',
    'VEHICULO',
    'ANIMAL',
    'VETERINARIO',
    'CELULAR',
    'TELEFONO',
    'PROGRAMACION',
    'TECLADO',
    'MONITOR',
    'MOUSE',
    'INTERNET',
    'SERVIDOR',
    'BASEDEDATOS',
    'ALGORITMO',
    'DESARROLLO',
    'APLICACION',
    'SOFTWARE',
    'HARDWARE',
    'ESTUDIANTE',
    'UNIVERSIDAD',
    'PROFESOR',
    'MATEMATICAS',
    'CIENCIA',
    'INGENIERIA',
    'TECNOLOGIA',
    'ROBOT',
    'SATELITE',
    'ASTRONAUTA',
    'PLANETA',
    'GALAXIA',
    'ESTRELLA',
    'OCEANO',
    'MONTAÑA',
    'BOSQUE',
    'RIO',
    'LAGUNA',
    'CIUDAD',
    'CARRETERA',
    'AVION',
    'HELICOPTERO',
    'BICICLETA',
    'MOTOCICLETA',
    'AUTOBUS',
    'TREN',
    'HOSPITAL',
    'MEDICINA',
    'ENFERMERO',
    'PACIENTE',
    'SALUD',

    // Anime
    'NARUTO',
    'SASUKE',
    'GOKU',
    'VEGETA',
    'SAITAMA',
    'ITACHI',
    'LUFFY',
    'DENJI',
    'GOJO',
    'EREN',
    'MIKASA',
    'LEVI',

    // Videojuegos
    'PIKACHU',
    'SONIC',
    'MARIO',
    'LUIGI',
    'ZELDA',
    'LINK',
    'KRATOS',
    'ATREUS',
    'MASTERCHIEF',
    'CYBERPUNK',
    'FORTNITE',
    'MINECRAFT',
    'PACMAN',
    'DONKEYKONG',

    // Películas / Superhéroes
    'SPIDERMAN',
    'BATMAN',
    'SUPERMAN',
    'JOKER',
    'THOR',
    'LOKI',
    'HULK',
    'IRONMAN',
    'CAPITANAMERICA',
    'BLACKPANTHER',
    'WOLVERINE',
    'DEADPOOL',
    'MATRIX',
    'TERMINATOR',
    'AVATAR',
    'TRANSFORMERS'
];


export function getRandomWord() {

    const randomIndex = Math.floor( Math.random() * words.length );

    return words[randomIndex];
}